apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nononode 
  janus-idp.io/tekton: nononode
  backstage.io/kubernetes-id: nononode
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nononode
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  