apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nononode
  janus-idp.io/tekton: nononode
  backstage.io/kubernetes-id: nononode
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nononode
resources:
- deployment.yaml
- route.yaml
- service.yaml
