apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: nononode
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nononode 
  name: nononode
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nononode
    weight: 100 
