apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nononode
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nononode 
  name: nononode
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nononode 
